### PR TITLE
Ignore comments when parsing recipient files

### LINKED ISSUE #2393: .gpg-id files with comments not handled correctly
### Summary
`pass` correctly ignores comments in `.gpg-id`, but `gopass` treats them as user IDs and this triggers GPG errors.

### Steps To Reproduce
1. Add a key with a comment to `.gpg-id`, e.g. `# EC9FB...`
2. Try to create/edit an entry
3. Get GPG error about `Invalid user ID`

### Gopass behavior
```
$ gopass edit  gentoo-infra/services/cdn77 
gpg: # EC9FB...: skipped: Invalid user ID
gpg: [stdin]: encryption failed: Invalid user ID
```

### Pass behavior
```
$ pass edit demo-secret
[master 117df28] Edit password for demo-secret using vim.
 1 file changed, 0 insertions(+), 0 deletions(-)
```

### Expected behavior
It should work, just like `pass`.

### Environment
- OS: Gentoo
- OS version: 5.18.REDACTED AMD Ryzen 7 3700X 8-Core Processor AuthenticAMD GNU/Linux
- gopass Version: 1.14.4
- Installation method: package manager

### PR DESCRIPTION
**Pull request by dominikschulz**
This implementation does not preserve comments, yet. That would require major changes to how recipients are currently handled.

Fixes #2393

RELEASE_NOTES=[ENHANCEMENT] Ignore comments in recipient files.

Signed-off-by: Dominik Schulz <dominik.schulz@gauner.org>

### CODE REVIEW

File: internal/recipients/recipients_test.go [hunk 1]
```diff
@@ -36,6 +61,10 @@ func TestUnmarshal(t *testing.T) {
 			in:   "foo@bar.com\rbaz@bar.com\r",
 			want: []string{"baz@bar.com", "foo@bar.com"},
 		},
+		{
+			in:   "# foo@bar.com\nbaz@bar.com\nzab@zab.com # comment",
+			want: []string{"baz@bar.com", "zab@zab.com"},
+		},
```
Comment (AnomalRoil) [inline internal/recipients/recipients_test.go:67]:
```suggestion
		{
			in:   "# foo@bar.com\nbaz@bar.com\nzab@zab.com # comment",
			want: []string{"baz@bar.com", "zab@zab.com"},
		},
		{
			in:   "# foo@bar.com\nbaz@bar.com\n# comment\nzab@zab.com\n",
			want: []string{"baz@bar.com", "zab@zab.com"},
		},
```

**Review by AnomalRoil — DISMISSED** [review]
