### PR TITLE
Use github.com/pquerna/otp to allow using the key period

### LINKED ISSUE #2276: TOTP `period` parameter is ignored
### Summary

I configure a TOTP token with a custom `period` (other than 30).

Unfortunately, gopass currently uses a hardcoded default value of 30:
https://github.com/gopasspw/gopass/blob/master/internal/action/otp.go#L23

### Steps To Reproduce

Add a secret with a TOTP and `period=60` like the following:

```
% gopass show testForGopassIssue 
Secret: testForGopassIssue

someSecretPassword
otpauth: //totp/demoTest?secret=bcde23456&algorithm=SHA256&digits=6&period=60
```
Then retrieve the current token:
```
% gopass otp testForGopassIssue
245371
This OTP password still lasts for:
]  3 / 29 [Goooooopass                                                                                              ]  10.34%
```

with a period of 30, instead of the period length of 60 given via the `otpauth://` URI.

### Expected behavior

Use the `period`-value as given via the `otpauth://` URI.

### Environment

- OS: Ubuntu 21.10
- OS version: Linux t480ssm 5.13.0-52-generic # 59-Ubuntu SMP Wed Jun 15 20:17:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- gopass Version: 1.14.0 go1.18 linux amd64
- Installation method: deb package diretly

### PR DESCRIPTION
**Pull request by dominikschulz**
RELEASE_NOTES=[BUGFIX] Use OTP key period

Fixes #2276

Signed-off-by: Dominik Schulz <dominik.schulz@gauner.org>

### CODE REVIEW

File: pkg/otp/otp.go [hunk 1]
```diff
@@ -31,12 +33,10 @@ func Calculate(name string, sec gopass.Secret) (twofactor.OTP, string, error) {
 	if otpURL != "" {
 		debug.Log("found otpauth url: %s", out.Secret(otpURL))
 
-		return twofactor.FromURL(otpURL) //nolint:wrapcheck
+		return otp.NewKeyFromURL(otpURL) //nolint:wrapcheck
```
Comment (AnomalRoil) [inline pkg/otp/otp.go:36]: My understanding it that this supports both TOTP and HOTP:
 https://github.com/pquerna/otp/blob/60112ee2a95553a491c22956619ef30260ec93e8/otp.go#L55

File: pkg/otp/otp.go [hunk 2]
```diff
@@ -45,47 +45,43 @@ func Calculate(name string, sec gopass.Secret) (twofactor.OTP, string, error) {
...
+		k, err := otp.NewKeyFromURL(secKey)
+		if err != nil {
+			return nil, fmt.Errorf("failed to parse otpauth URL: %w", err)
+		}
+
+		return k, nil
 	}
 
-	otp, err := twofactor.NewGoogleTOTP(twofactor.Pad(secKey))
+	debug.Log("assembling otpauth URL from secret only (%q), using defaults", out.Secret(secKey))
```
Comment (AnomalRoil) [inline pkg/otp/otp.go:58]: This is logging a secret, not great.

File: pkg/otp/otp.go [hunk 3]
```diff
@@ -45,47 +45,43 @@ func Calculate(name string, sec gopass.Secret) (twofactor.OTP, string, error) {
...
+
+	// otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example
+	key, err := otp.NewKeyFromURL(fmt.Sprintf("otpauth://totp/new?secret=%s&issuer=gopass", secKey))
```
Comment (AnomalRoil) [inline pkg/otp/otp.go:61]: This is not supporting HOTP, we might want to errror out if HOTP was requested, no?

File: internal/action/otp.go [hunk 4]
```diff
@@ -108,18 +105,30 @@ func (s *Action) otp(ctx context.Context, name, qrf string, clip, pw, recurse bo
 			return nil
 		default:
 		}
-		two, label, err := otp.Calculate(name, sec)
+
+		two, err := otp.Calculate(name, sec)
```
Comment (AnomalRoil) [inline internal/action/otp.go:109]: `two` supports both HOTP and TOTP as per the doc of `pquerna/otp` if it took the happy path where the URL is parsed easily in `otp.Calculate`.

File: internal/action/otp.go [hunk 5]
```diff
@@ -108,18 +105,30 @@ func (s *Action) otp(ctx context.Context, name, qrf string, clip, pw, recurse bo
...
 		if err != nil {
 			return exit.Error(exit.Unknown, err, "No OTP entry found for %s: %s", name, err)
 		}
-		token := two.OTP()
+
+		token, err := totp.GenerateCodeCustom(two.Secret(), time.Now(), totp.ValidateOpts{
```
Comment (AnomalRoil) [inline internal/action/otp.go:114]: I guess we might want to switch on:
https://github.com/pquerna/otp/blob/60112ee2a95553a491c22956619ef30260ec93e8/otp.go#L99

if we really want to support both HOTP and TOTP.

**Comment by AnomalRoil** [comment]
So, my tests show that the old binary and the new binary both work fine with TOTP and give the same value as Google Authenticator.

But the HOTP part isn't working with the new binary.

File: pkg/otp/otp.go (hunk 2 above)
Comment (dominikschulz) [reply pkg/otp/otp.go:58]: Yes, it's logging a secret. But it's doing so responsibly. See https://github.com/gopasspw/gopass/blob/master/pkg/debug/debug.go#L210 and https://github.com/gopasspw/gopass/blob/master/internal/out/print.go#L27.

File: internal/action/otp.go (hunk 5 above)
Comment (dominikschulz) [reply internal/action/otp.go:114]: Done.

File: pkg/otp/otp.go (hunk 1 above)
Comment (dominikschulz) [reply pkg/otp/otp.go:36]: Both should work, yes.

File: pkg/otp/otp.go (hunk 3 above)
Comment (dominikschulz) [reply pkg/otp/otp.go:61]: How would we know that HOTP was requested?

**Comment by dominikschulz** [comment]
I'm not sure if I ever used HTOP. Do you have an example that I could use to reproduce the issue?

File: pkg/otp/otp.go (hunk 3 above)
Comment (AnomalRoil) [reply pkg/otp/otp.go:61]: The URL changes, it says "otpauth://hotp" instead.
Or we use the KV `hotp` instead of `otpauth` or `totp`.

Also I guess just relying on the library's `Type` method should be enough.

**Comment by AnomalRoil** [comment]
I guess
`otpauth://hotp/hotp@example.com?secret=N6CIHPYDGHI6QC4ZV7Q3S3FXA22BZOCY&issuer=example.com&digits=6&algorithm=SHA1&counter=1` should work.

Old binary gives `683787` with `&counter=1` and `044228` with `&counter=2`

File: internal/action/otp.go [hunk 6]
```diff
@@ -111,14 +112,27 @@ func (s *Action) otp(ctx context.Context, name, qrf string, clip, pw, recurse bo
...
+				Period:    uint(two.Period()),
+				Skew:      1,
+				Digits:    potp.DigitsSix,
+				Algorithm: potp.AlgorithmSHA1,
+			})
+			if err != nil {
+				return exit.Error(exit.Unknown, err, "Failed to compute OTP token for %s: %s", name, err)
+			}
+		case "hotp":
+			// TODO: Counter shouldn't be fixed.
```
Comment (AnomalRoil) [inline internal/action/otp.go:128]: Maybe we should just prompt the user for their input for the counter?

File: internal/action/otp.go [hunk 7]
```diff
@@ -111,14 +112,27 @@ func (s *Action) otp(ctx context.Context, name, qrf string, clip, pw, recurse bo
...
+			token, err = hotp.GenerateCodeCustom(two.Secret(), 1, hotp.ValidateOpts{
+				Digits:    potp.DigitsSix,
+				Algorithm: potp.AlgorithmSHA1,
```
Comment (AnomalRoil) [inline internal/action/otp.go:131]: Actually this is sometimes contained in the URL sometimes. But I guess we could just say "not supported but for SHA1"?

**Review by AnomalRoil — DISMISSED** [review]

File: pkg/otp/otp.go (hunk 3 above)
Comment (dominikschulz) [reply pkg/otp/otp.go:61]: Actually this is only the fallback. If we end up having only the secret we can only assume that it's TOTP. Everything else would require information we just don't have.

Maybe it's not worth keeping this fallback after all. But I guess somebody would complain if we drop it.

File: internal/action/otp.go (hunk 7 above)
Comment (dominikschulz) [reply internal/action/otp.go:131]: Done.

File: internal/action/otp.go (hunk 6 above)
Comment (dominikschulz) [reply internal/action/otp.go:128]: I think we actually need to keep track of the counter, don't we?

**Review by AnomalRoil — APPROVED** [review]
