### PR TITLE
Do not recurse when deleting a key

### LINKED ISSUE #1906: `gopass rm -r folder foo` deletes folder right away (non interactive)
### Summary

`gopass rm -r folder` ask for confirmation but `gopass rm -r folder foo` does not.

### Steps To Reproduce

`gopass rm -r folder foo`

### Expected behavior

`gopass rm` without the flag `-f` should reliably prompt for confirmation before deleting anything.

### Environment

- OS: Arch Linux
- gopass Version: 1.12.5
- Installation method: OS package manager pacman

Thank you very much for the work you put into this project.

### PR DESCRIPTION
**Pull request by dominikschulz**
Fixes #1906

RELEASE_NOTES=[BUGFIX] Do not recurse with a key

Signed-off-by: Dominik Schulz <dominik.schulz@gauner.org>

### CODE REVIEW

File: internal/action/delete.go [hunk 1]
```diff
@@ -39,7 +43,7 @@ func (s *Action) Delete(c *cli.Context) error {
 		}
 	}
 
-	if recursive {
+	if recursive && key == "" {
```
Comment (AnomalRoil) [inline internal/action/delete.go:46]: This is unnecessary since it would have returned earlier otherwise, but I guess it won't hurt.

**Review by AnomalRoil — APPROVED** [review]
