### PR TITLE
Better progress bar handling for OTP

### LINKED ISSUE #2017: Add config option to output otp-code only
### Summary

- https://github.com/gopasspw/gopass/issues/1150
- I need to output otp password only as default.
- [aws-vault](https://github.com/99designs/aws-vault/blob/master/USAGE.md) supports `pass` for MFA prompt. But I cannot use `gopass` for MFA prompt of aws-vault with following error.

```bash
2021/10/24 17:56:05 aws-vault 6.3.1-Homebrew
2021/10/24 17:56:05 Loading config file /Users/claud/.aws/config
2021/10/24 17:56:05 Parsing config file /Users/claud/.aws/config
2021/10/24 17:56:05 [keyring] Considering backends: [pass]
2021/10/24 17:56:05 profile claud: using stored credentials
2021/10/24 17:56:05 profile claud: using GetSessionToken (with MFA)
2021/10/24 17:56:05 Fetching MFA code using `pass otp arn:aws:iam::xxxxxxxxxxxx:mfa/xxxxxxxxxxxxx`
2021/10/24 17:56:05 Using STS endpoint https://sts.ap-northeast-2.amazonaws.com
2021/10/24 17:56:05 Looking up keyring for 'claud'
aws-vault: error: exec: Failed to get credentials for claud: ValidationError: 2 validation errors detected: Value '976249 lasts 24s 	|------========================|' at 'tokenCode' failed to satisfy constraint: Member must have length less than or equal to 6; Value '976249 lasts 24s 	|------========================|' at 'tokenCode' failed to satisfy constraint: Member must satisfy regular expression pattern: [\d]*
	status code: 400, request id: 5a48f167-36d6-4b7f-97ce-1cdededc9f5c
```

### PR DESCRIPTION
**Pull request by AnomalRoil**
RELEASE_NOTES=[BUGFIX] Do not print OTP progress bar if not in terminal
RELEASE_NOTES=[UX] Use new progress bar for OTP expiry time

This is making the expiry time for OTP visually go from 0 to expiry time in terminal, but prevents printing the progress bar when not in a terminal.

image

I also replaced the special handling of the remaining time until expiry to use `Truncate` instead.

Sadly, I'm yet again adding some "special handling" to detect whether we are in a terminal or not. We might want to heavily refactor all such things.

This fixes #2017.

### CODE REVIEW

File: internal/action/otp.go [hunk 1]
```diff
@@ -48,32 +49,61 @@ func (s *Action) otp(ctx context.Context, name, qrf string, clip, pw, recurse bo
...
 	if clip {
 		if err := clipboard.CopyTo(ctx, fmt.Sprintf("token for %s", name), []byte(token), s.cfg.ClipTimeout); err != nil {
 			return ExitError(ExitIO, err, "failed to copy to clipboard: %s", err)
 		}
-		return nil
+	}
+
+	done := make(chan bool)
+	skip := false
+	// let us check we are not in pw or in qr code mode and are not being redirected to a pipe
```
Comment (dominikschulz) [inline internal/action/otp.go:63]: I'd love to be reminded what `pw` mode means here.

File: internal/action/otp.go [hunk 2]
```diff
@@ -48,32 +49,61 @@ func (s *Action) otp(ctx context.Context, name, qrf string, clip, pw, recurse bo
...
+	o, _ := os.Stdout.Stat()
+	if pw || qrf != "" || (o.Mode()&os.ModeCharDevice) != os.ModeCharDevice {
```
Comment (dominikschulz) [inline internal/action/otp.go:65]: The third condition might better go into a small function call?

File: internal/action/otp.go [hunk 3]
```diff
@@ -48,32 +49,61 @@ func (s *Action) otp(ctx context.Context, name, qrf string, clip, pw, recurse bo
...
+		out.Printf(ctx, "%s", token)
+		skip = true
+	} else { // if not then we want to print a progress bar with the expiry time
+		out.Printf(ctx, "%s", token)
+		out.Warningf(ctx, "This OTP password still lasts for:", nil)
+		bar := termio.NewProgressBar(int64(secondsLeft))
+		bar.Hidden = ctxutil.IsHidden(ctx)
+		if !bar.Hidden {
```
Comment (dominikschulz) [inline internal/action/otp.go:73]: Since we're going to have both branches anyway we might want to swap them to handle the true case first.

**Review by dominikschulz — APPROVED** [review]
Looks good, thanks. But I'd suggest some small changes.

**Review by dominikschulz — APPROVED** [review]
Thanks!

**Comment by posquit0** [comment]
Is there any release schedule? I wanna use this feature! 😆

**Comment by dominikschulz** [comment]
Cutting new releases has become very easy. We can do one soon. Probably this week.

**Comment by dominikschulz** [comment]
@AnomalRoil ?

Personally I don't put OTP into my stores so I don't use this.

**Comment by AnomalRoil** [comment]
Mhhh I personally never use the interactive shell, so I didn't realize we needed a way to do that.
I could had a key binding to q maybe to quit it?

**Comment by mirkonasato** [comment]
`q` to quit would be great!

**Comment by dominikschulz** [comment]
@mirkonasato I'm sorry for that inconvenience. I have just reproduced it and we definitely need a way to abort the progress bar w/o killing gopass.

**Comment by AnomalRoil** [comment]
I've added a fix in #2041. 👍🏻
