### PR TITLE
Handle from prefix correctly during move

### LINKED ISSUE #2079: Gopass `mv` moves fuzzy names even on exact match and doesn't rename directories
### Steps To Reproduce
```
$ GOPASS_HOMEDIR=~/test gop generate comm/test 12 
$ GOPASS_HOMEDIR=~/test gop generate comm/test2 12
$ GOPASS_HOMEDIR=~/test gop generate communication/t1 12
$ GOPASS_HOMEDIR=~/test gop ls
gopass
 ├── communication/
 │          └── t1
 └── comm/
        ├── test
        └── test2
       
$ GOPASS_HOMEDIR=~/test gop mv comm email 
$ GOPASS_HOMEDIR=~/test gop ls
gopass
└── email/
    └── comm/
        ├── test
        ├── test2
        └── unication/
            └── t1
```

### Expected behavior

Should get instead:
```
$ GOPASS_HOMEDIR=~/test gop ls
gopass
 ├── communication/
 │          └── t1
 └── email/
        ├── test
        └── test2
       
```

Notice also that the folder `comm` wasn't renamed but actually moved into a new folder instead.

This is not similar to how Unix's `mv`works, which is what we aim for with `gopass mv` IIRC.

### PR DESCRIPTION
**Pull request by dominikschulz**
Fixes #2079

RELEASE_NOTES=[BUGFIX] Handle from prefix correctly on mv

Signed-off-by: Dominik Schulz <dominik.schulz@gauner.org>

### CODE REVIEW

File: internal/store/root/move.go [hunk 1]
```diff
@@ -156,6 +147,43 @@ func (r *Store) moveFromTo(ctx context.Context, subFrom *leaf.Store, from, to, f
...
+		dstIsDir = false
+		to = ""
+	}
+
+	// are we moving into an existing directory? Then we just need to prepend
+	// it's name to the source.
+	// a -> b
+	// - a/f1 -> b/a/f1
+	// a -> b
+	// - a -> b/a
```
Comment (AnomalRoil) [inline internal/store/root/move.go:162]: Wow, I've no idea what that means.

`mv a b` on a tree with a/f1 inside of a?
And same but for just an entry named a?

File: internal/store/root/move.go [hunk 2]
```diff
@@ -156,6 +147,43 @@ func (r *Store) moveFromTo(ctx context.Context, subFrom *leaf.Store, from, to, f
...
+	// are we moving a simple file? that's easy
+	if !srcIsDir {
+		// otherwise we just rename a file to another name
+		return to
+	}
+
+	// move a/ b, where a is a directory with a trailing slash and b
+	// does not exist, i.e. move a to b
+	if strings.HasSuffix(from, "/") {
+		return path.Join(to, strings.TrimPrefix(src, from))
```
Comment (AnomalRoil) [inline internal/store/root/move.go:179]: I don't see any difference with the "else" path that returns the same thing, no?

Is this if clause necessary?

**Review by AnomalRoil — APPROVED** [review]
