### PR TITLE
Do not omit shadowed entries in ls output

### LINKED ISSUE #2338: `gopass list --flat` doesn't show secrets with the same names as folders
### Summary
If a secret has the same name as a folder, it won't be listed by `gopass list --flat`.

### Steps To Reproduce

```
gopass add foo/bar
gopass add foo/bar/baz
gopass list --flat
```

### Expected behavior

Should return:
```
foo/bar
foo/bar/baz
```

### Environment

- OS: NixOS
- OS version: 22.11
- gopass Version: 1.14.5
- Installation method: Nixpkgs

### PR DESCRIPTION
**Pull request by dominikschulz**
Fixes #2338

RELEASE_NOTES=[BUGFIX] Do not shadow entries behind folders.

Signed-off-by: Dominik Schulz <dominik.schulz@gauner.org>

### CODE REVIEW

File: internal/tree/node.go [hunk 1]
```diff
@@ -59,6 +61,40 @@ func (n Node) Equals(other Node) bool {
 	return true
 }
 
+func (n Node) Merge(other Node) *Node {
```
Comment (dominikschulz) [inline internal/tree/node.go:64]: This method needs some more explanation.

File: internal/tree/node.go [hunk 2]
```diff
@@ -113,7 +153,7 @@ func (n *Node) format(prefix string, last bool, maxDepth, curDepth int) string {
 
 // Len returns the length of this subtree.
 func (n *Node) Len() int {
-	if n.Type == "file" {
+	if n.Subtree == nil {
 		return 1
 	}
```
Comment (dominikschulz) [inline internal/tree/node.go:159]: We need to add 1 to l if n.Leaf is true.

File: internal/tree/root.go [hunk 3]
```diff
@@ -80,11 +82,15 @@ func (r *Root) insert(path string, template bool, mountPath string) error {
...
+		debug.Log("[%d] %s -> Node: %+v", i, e, n)
+
+		node := t.Insert(n)
+		debug.Log("node after insert: %+v", node)
+
 		// do we need to extend an existing subtree?
 		if i < len(p)-1 && node.Subtree == nil {
 			node.Subtree = NewTree()
-			node.Type = "dir"
+			// node.Type = "dir"
```
Comment (dominikschulz) [inline internal/tree/root.go:93]: Remove this.

File: internal/tree/tree.go [hunk 4]
```diff
@@ -44,28 +46,27 @@ func (t *Tree) Equals(other *Tree) bool {
 }
 
 // Insert adds a new node at the right position.
-func (t *Tree) Insert(node *Node) (*Node, error) {
-	pos, found := t.find(node.Name)
+func (t *Tree) Insert(node *Node) *Node {
+	pos, found := t.findPositionFor(node.Name)
```
Comment (dominikschulz) [inline internal/tree/tree.go:50]: `found` implies this to be a bool. Maybe we call it `existing` or something.
